### PR TITLE
[SC-407] Improving Coverage

### PR DESCRIPTION
**Pull request by hexonaut**
Coverage has dropped below 90%. Doing a round of fixes.

### CODE REVIEW

**Review by lucas-manuel — CHANGES_REQUESTED** [review]
```solidity
    function test_constructor() public {
        DSROracleReceiverGnosis receiver = new DSROracleReceiverGnosis(AMB, 1, address(forwarder), oracle);

        assertEq(address(receiver.oracle()),        address(oracle));
        assertEq(address(receiver.l2CrossDomain()), address(AMB));
        assertEq(receiver.chainId(),                bytes32(uint256(1)));
        assertEq(receiver.l1Authority(),            address(forwarder));
    }
```

Adding a test like this for all receivers under `setUpDomain` will fix the constructor missing coverage

**Comment by lucas-manuel** [comment]
> ```solidity
>     function test_constructor() public {
>         DSROracleReceiverGnosis receiver = new DSROracleReceiverGnosis(AMB, 1, address(forwarder), oracle);
> 
>         assertEq(address(receiver.oracle()),        address(oracle));
>         assertEq(address(receiver.l2CrossDomain()), address(AMB));
>         assertEq(receiver.chainId(),                bytes32(uint256(1)));
>         assertEq(receiver.l1Authority(),            address(forwarder));
>     }
> ```
> 
> Adding a test like this for all receivers under `setUpDomain` will fix the constructor missing coverage

Same with forwarder and adapter

**Comment by hexonaut** [comment]
Not sure about this weird issue with optimism forwarder. Can investigate outside this PR.

**Review by barrutko — APPROVED** [review]
New tests and upped coverage looks good.
I'm fine with investigating Optimism issue in later PR.

**Review by lucas-manuel — APPROVED** [review]

**Pull request merged**
